---
- hosts: all
  become: yes
  vars: 
    ansible_ssh_user:root
    ansible_ssh_pass:electric dancy pants
  roles:
    - role: 
    - role:
  tasks:
    - name: wheel group
      group:
        name=wheel
        state=present
    - name: allow wheel group to have sudo privligaes.
      lineinfile:
        dest=/etc/sudoers
        state:present
        regexp='^%wheel'
line: '%wheel ALL=(ALL) NOPASSWD : ALL'

    - name : add manager with sudo privliges
      user: name=manager groups=wheel append=yes state=present createhome=yes


    - name : install packages mtr, tcpdump , nano and cowsay.
      yum: state=present name={{ items }}
      with items:
-mtr
-tcpdump
-nano
-cowsay
- nmcli:
    conn_name: my-eth1
    dns4:
     - 10.0.5.1
     - 209.244.0.3
    state : present
